apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: chaos-poc
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: chaos-poc
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8081
    targetPort: 8081
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: chaos-poc
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
